### ISSUE TITLE
Communication Hardware

### ISSUE THREAD

**Issue by sisodiakaran** [jrbenito/ABBAurora#2]
Hi, thanks for sharing this library. However I would like to know the connectivity hardware information. For example to communicate with standred modbus we generally use Max485 chip with half duplex mode. So the third pin is used to switch between the Receive and Transmit operations (I can't see use of the third pin in the example). 
I am wondring if I can use same hardware to communicate with the Aurora protocol as well. 

Thanks...

**Comment by jrbenito** [comment]
Hi @sisodiakaran ,

You are correct, a third pin is used to control TX/RX of RS485 interface. At this time it is hardcoded to pin #5 at library configuration (https://github.com/jrbenito/ABBAurora/blob/2c9cfb026f141654b2c91e13fbd61a483a0fd8d8/ABBAurora.h#L7)

This should be modified to configurable by the user.
