### ISSUE TITLE
ABB sells a converter from Modbus RTU to Modbus TCP/IP

### ISSUE THREAD

**Issue by sisodiakaran** [jrbenito/ABBAurora#3]
HI, Just wondering if this library requires a converter or not? Or this could be used directly with inverter ports?

1) Inverter -> converter -> Max485 -> Arduino
or
2) Inverter  -> Max485 -> Arduino

Hopping for option 2 :D

**Comment by jrbenito** [comment]
Hi @sisodiakaran ,

Option 2 (Inverter -> MAX485 -> Arduino Serial/software serial)

**Comment by jrbenito** [comment]
Btw, worth mention that option one as you suggested would require TCP/IP connection on the Arduino. (not practical)

**Comment by sisodiakaran** [comment]
Ahh! Yes, you are right about TCP/IP. Actually, the converter is very costly (~$360) that's why I was searching for alternatives. Then I found this awesome library, thanks for the hard work :)

Between I am unable to find relevant documentation for Aurora Protocol on the internet where I can see the data structure of the registers.
